[mcp]

[mcp.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]

[mcp.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp.brave-search]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-brave-search"]
